### ISSUE TITLE
prevent thumb.db files being released

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/osrelease#71]
Following slack discussion here: https://bennettoxford.slack.com/archives/C63UXGB8E/p1684504187784809

We should remove previously released thumb files for released (=> approved) images, and prevent thumb files from being released in future

**Comment by LFISHER7** [comment]
More generally, we're now much [more explicit about allowed file types in the docs](https://docs.opensafely.org/releasing-files/#allowed-file-types), which should be enforced by osrelease

**Comment by bloodearnest** [comment]
Fixes in #76
